### ISSUE TITLE
Incorrect allocation factors after conversion using plug-in

### ISSUE THREAD

**Issue by davidemeyer** [GreenDelta/olca-app#1]
I converted a data set with allocation factors from version 1.3 to 1.4 using the database conversion plug-in provided. I noticed that the allocation factors were incorrect (some were zeroed out) after conversion. I exported the affected processes as ecospold1 files and imported them individually into version 1.4 to correct the issue.

**Comment by msrocka** [comment]
Since openLCA 1.4, it is possible to store allocation factors for different allocation methods (physical, economic, and causal allocation) in the same process. In openLCA 1.3, allocation factors could be only stored for a single method per process. Thus, the allocation factors for the other methods were sometimes zero (other factors were maybe calculated with wrong assumptions). Since openLCA 1.3 is not supported anymore, I am closing this issue now.
