### ISSUE TITLE
SimaPro import with duplicates

### ISSUE THREAD

**Issue by bkuczenski** [GreenDelta/olca-app#119]
I am importing a few datasets exported as SimaPro CSVs- it seems the datasets are very large (14MB) and each seems to contain an entire copy of ecoinvent (plus one distinct process in each file).

When doing the import I see two problems: first, the console is filled with these messages:
    948353 [Thread-18] WARN org.openlca.io.simapro.csv.input.ProcessHandler  - a process with the identifier e03af539-ce40-3dd1-ba03-314c0162ff8d is already in the database and was not imported

I imagine that the entire ecoinvent database was imported 4x-- this means around 50,000 log messages which caused a significant performance stress on the console. 

However, when I inspect the database I now find four duplicates of each process (see screenshot). I don't know an easy way to count the number of activities in the database, or to compare two different activities, but it seems they are all duplicated (identical UUIDs and apparently identical exchanges). Flows were not duplicated. 

Not sure what the correct approach is- but having duplicate processes seems like a bad idea whether the exchange data are identical or not. Also, the log message seems to be incorrect since the duplicates were imported. 
![Screenshot from 2020-10-05 10-08-52](https://user-images.githubusercontent.com/2121413/95111170-fa3c2f80-06f3-11eb-88e4-34bd17fe4cd1.png)

**Comment by msrocka** [comment]
Right, the console was really a bottleneck regarding the performance. This should  be fixed in the current master branch where a limit is set for the console buffer now: https://github.com/GreenDelta/olca-app/blob/master/olca-app/src/org/openlca/app/logging/Console.java#L64

Regarding the duplicate imports, an early return statement was missing, which should be fixed with this commit now: https://github.com/GreenDelta/olca-modules/commit/ec262dacaeff78091e739e91814c77ffb339bc39

Both things should be fixed in the next openLCA 2.0.x build.

**Comment by msrocka** [comment]
This should be fixed in the current [beta version](https://share.greendelta.com/index.php/s/76uAFtMKDIWGoXC). If this is not the case, feel free to reopen this issue.
