### ISSUE TITLE
ECOSPOLD2 files import error

### ISSUE THREAD

**Issue by ankur-paan** [GreenDelta/olca-app#342]
# Error description

I tried to import dataset downloaded from ecoinvent website directly in ecospold2 format but openLCA threw an error.

# Steps to reproduce

1. download any ecospold2 format dataset from ecoinvent 3.9.1
2. try to import in openlca

# Attached files

example dataset in ecospold2 format
[2023-08-02_ecoSpold.spold.zip](https://github.com/GreenDelta/olca-app/files/12245172/2023-08-02_ecoSpold.spold.zip)

# openLCA error message

Could not find import wizard wizard.import.ecospold2

# Installation details

* openLCA version: 2.0.1
* operating system: Windows 11
* os architecture: amd64
* os version: 10.0
* native libraries loaded: true
* with sparse matrix support: false

# Full error stack trace

```
not available
```

**Comment by msrocka** [comment]
Thanks, openLCA will show the message box below in the next version. We do not support the direct import of EcoSpold 2 data sets because they come typically only from ecoinvent. ecoinvent databases for openLCA are available on [openLCA Nexus](https://nexus.openlca.org/).

![image](https://github.com/GreenDelta/olca-app/assets/3520062/32f5ab16-df38-4dd0-94e8-c0edb1cc08b7)
