### ISSUE TITLE
Flow mapping a technosphere flow does not update the allocation table

### ISSUE THREAD

**Issue by bl-young** [GreenDelta/olca-app#429]
I would think the expected outcome would be that the mapped flow has the same causal allocation before and after mapping.

**Comment by msrocka** [comment]
Do you mean in the flow mapping tool or in the "bulk replace" tool? In the "bulk replace" tool, allocation factors are currently not updated, that should be fixed in the next version.

In the mapping tool, it works for me in a quick test. I create the example below in the openLCA script editor, I open the process P, calculate allocation factors, then replace flows b with c via the mapping. When I then reload P, c has the allocation factors of b. 

```python
units = UnitGroup.of("Mass units", "kg")
mass = FlowProperty.of("Mass", units)
a = Flow.product("a", mass)
b = Flow.product("b", mass)
c = Flow.product("c", mass)
e = Flow.elementary("e", mass)

P = Process.of("P", a)
P.output(b, 1.0)
P.output(e, 1.0)

db.insert(units, mass, a, b, c, e, P)
App.runInUI("Update navi...", lambda: Navigator.refresh())
```

**Comment by bl-young** [comment]
Yes, the flow mapping tool. But let us go back and try to recreate. We were noticing this predominantly with flows that had been mapped. @pweilerERG

**Comment by bl-young** [comment]
ok maybe we misidentified the source of our issue as we did some tests and agree it appears to be working correctly
