### ISSUE TITLE
Rework allocation to be "by property"

### ISSUE THREAD

**Issue by bkuczenski** [GreenDelta/olca-app#83]
There is no meaningful *functional* difference between physical and economic allocation-- all it does is choose one flow property or another to determine allocation factors. But at present it is left to the app to figure out which flow property to use. 

For instance, the user manual says: " In order for allocation to work, the main product and the co-products of the multioutput process need to have the same flow property." In other words, the app is inspecting the process and deciding what property to use for allocation. Similarly, for economic allocation the flow property being used is unclear, but is apparently required to be "Market value, bulk prices," leading to problems like [this one](https://ask.openlca.org/1557/switching-between-allocation-methods?show=1557#q1557). and leading to annoyances if using a process whose flows are not characterized by that quantity.

The proposed solution would be to replace "physical | economic | causal" allocation to be "allocation by property | causal", and if "allocation by property" is chosen, then the UI offers a drop-down for *all eligible properties*, i.e. all properties that are characterized for *all* reference flows, being physical, economic, social, whatever. Then the user picks the quantity to use. This also has the advantage of providing immediate feedback to the user about how the allocation calculation is being performed.

By the way, I would also recommend a more tolerant allocation algorithm that does not *require* all outputs to be characterized by the same flow property, but simply assigns allocation factors of zero to all flows not characterized by the designated property.  In this case, "all eligible properties" would be any property that appears on *any* reference flow, not any property that appears on *all* reference flows.

**Comment by msrocka** [comment]
I think the problem with the economic allocation factors is related to the fact that the products need to have a common flow property which is tagged as `economic` (which is the case for `Market value, bulk prices` but not limited to that)…

But I agree (and `+1`): selecting the property that should be used for the calculation of the factors (with a more tolerant algorithm) would be much better.

I would still keep the categories `economic`, `physical`, and `causal` because this is then used in the calculation setup of a product system to decide which factors should be selected in the calculation for the respective processes (where each process could have different properties from which these allocation factors are derived).

Also note that the factors can be set/edited manually and that there is also this issue #31.

**Comment by msrocka** [comment]
In openLCA 2 ([beta1](https://share.greendelta.com/index.php/s/76uAFtMKDIWGoXC)), this is better now: you can select the properties that should be used for calculating the allocation factors:

![image](https://user-images.githubusercontent.com/3520062/181748830-966b3e61-723b-43dd-8c47-98b43899c2ce.png)

Also, you can always just enter the factors manually without using that dialog. The factors are shown in red when they do not sum up to 1.
